name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Static code analysis
        run: npm run lint --if-present

      - name: Build Angular app
        run: |
          npm run build -- --configuration production --base-href "/${{ github.event.repository.name }}/"
        env:
          GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}

      - name: Run tests
        run: npm run test --if-present

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/google-contacts-sync/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
